#!/bin/bash
#! This line is a comment
#! Make sure you only have comments and #SBATCH directives between here and the end of the #SBATCH directives, or things will break
#! Name of the job:
#SBATCH -J  flat_sky_norm
#! Account name for group, use SL2 for paying queue:
#SBATCH -A DIRAC-DP002-CPU
#! Output filename:
#! %A means slurm job ID and %a means array index
#SBATCH --output=logfiles/flat_sky_norm_%A_%a.out
#! Errors filename:
#SBATCH --error=logfiles/flat_sky_norm_%A_%a.err


#! Number of nodes to be allocated for the job (for single core jobs always leave this at 1)
#SBATCH --nodes=1
#! Number of tasks. By default SLURM assumes 1 task per node and 1 CPU per task. (for single core jobs always leave this at 1)
#SBATCH --ntasks=1
#! How many many cores will be allocated per task? (for single core jobs always leave this at 1)
#SBATCH --cpus-per-task=32
#! Estimated runtime: hh:mm:ss (job is force-stopped after if exceeded):
#SBATCH --time=8:00:00
#! Estimated maximum memory needed (job is force-stopped if exceeded):
#! RAM is allocated in ~5980mb blocks, you are charged per block used,
#! and unused fractions of blocks will not be usable by others.
#SBATCH --mem=20000mb

#! This is the partition name.
#SBATCH -p icelake

#! mail alert at start, end and abortion of execution
#! emails will default to going to your email address
#! you can specify a different email address manually if needed.
##SBATCH --mail-type=ALL

#! Don't put any #SBATCH directives below this line

#! The variable $SLURM_ARRAY_TASK_ID contains the array index for each job.
#! In this example, each job will be passed its index, so each output file will contain a different value
echo "This is job" $SLURM_ARRAY_TASK_ID

# Create logfiles directory if it doesn't exist
mkdir -p logfiles

module purge
module load rhel7/default-peta4 
source ~/.bashrc
conda activate cmplx_fld_lensplus

#! Command line that we want to run:
# Set the number of processes to match SLURM allocation
export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
python flat_sky_normalisation.py


